version: "3"
services:
    web:
        image: nginx:1.21.6
        container_name: ulang_nginx
        restart: always
        links:
            - site
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./data/logs:/logs
            - ../..:/ulang
        networks:
            - ulang_network
    site:
        build:
            dockerfile: Dockerfile.site
            context: .
        container_name: ulang_site
        restart: always
        links:
            - database
        environment:
            - EMSDK=/emsdk
            - ULANG_CLIENT_SECRET=${ULANG_CLIENT_SECRET}
            - ULANG_CLIENT_ID=${ULANG_CLIENT_ID}
            - ULANG_DATA_DIR=${ULANG_DATA_DIR}
            - ULANG_DB_PASSWORD=${ULANG_DB_PASSWORD}
        volumes:
            - ../..:/ulang
        networks:
            - ulang_network
    database:
        image: mariadb:latest
        container_name: ulang_db
        user: badlogic
        environment:
            MARIADB_ROOT_PASSWORD: ${ULANG_DB_PASSWORD}
            MARIADB_DATABASE: ulang
        volumes:
            - ./data/db:/var/lib/mysql
            - ../server/ulang-db.conf:/etc/mysql/conf.d/ulang-db.conf
        networks:
            - ulang_network
networks:
    ulang_network:
        driver: bridge
