FROM node:16

RUN git clone https://github.com/badlogic/ulang-vm /ulang
RUN git clone https://github.com/emscripten-core/emsdk.git /emsdk && cd /emsdk && git pull && ./emsdk install latest && ./emsdk activate latest
WORKDIR /ulang/wasm
ENTRYPOINT ["./docker/main.sh"]