version: "3"
services:
    web:
        image: nginx:latest
        container_name: ulang_nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf            
            - ./data/logs:/logs
        environment:
            VIRTUAL_HOST: ulang.io,www.ulang.io
            LETSENCRYPT_HOST: ulang.io,www.ulang.io
            LETSENCRYPT_EMAIL: "badlogicgames@gmail.com"   
    site:
        build:
            dockerfile: Dockerfile.site
            context: .
        container_name: ulang_site
        restart: always        
        environment:
            - ULANG_RESTART_PWD=${ULANG_RESTART_PWD}
            - EMSDK=/emsdk
networks:
    default:
        external:
            name: nginx-proxy