version: "3"
services:
    web:
        environment:
            VIRTUAL_HOST: ulang.io,www.ulang.io
            LETSENCRYPT_HOST: ulang.io,www.ulang.io
            LETSENCRYPT_EMAIL: "badlogicgames@gmail.com"
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: nginx-proxy
