version: "3"
services:
  web:
    ports:
      - 3000:80
  site:
    ports:
      - 9229:9229
    environment:
      - ULANG_DEV=true
      - ULANG_CLIENT_SECRET_DEV=${ULANG_CLIENT_SECRET_DEV}
      - ULANG_CLIENT_ID_DEV=${ULANG_CLIENT_ID_DEV}
      - ULANG_DATA_DIR=${ULANG_DATA_DIR}
