FROM node:16

RUN mkdir -p /ulang
RUN groupadd -g 999 ulang
RUN useradd -r -u 999 -g ulang ulang
RUN chown -R ulang:ulang /ulang
USER ulang:ulang

WORKDIR /ulang
RUN ls -lah /ulang
RUN git clone https://github.com/emscripten-core/emsdk.git emsdk && cd emsdk && git pull && ./emsdk install latest && ./emsdk activate latest
ENTRYPOINT ["./wasm/docker/main.sh"]